services:
  mongo:
    image: mongo:7
    container_name: id3a-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - id3a_mongo_data:/data/db

volumes:
  id3a_mongo_data:
