/**
 * Idea Wizard service.
 *
 * Flow:
 *   1. The user types a one-line seed when creating the project.
 *   2. The wizard walks them through 7 fixed questions, each rendered with
 *      adaptive copy/options/defaults generated by Gemini 3.1 Flash so the
 *      experience feels tailored without becoming an unbounded chat.
 *   3. On `finalizeStyleSheet`, Gemini 3.1 Pro produces a frozen styleSheet
 *      JSON that is injected into every downstream model call.
 *
 * Question schedule (fixed order; the user cannot skip):
 *   audience → tone → lengthSec → keyPoints → visualAesthetic → voiceMood → musicVibe
 */

import { structuredJSON } from './openrouter.js';

// Both wizard calls go through the same verified Pro text route. The Flash
// preview text variant 400'd on this account; sticking with one working model
// keeps the wizard reliable.
const PRO_MODEL = 'google/gemini-3.1-pro-preview';

export const QUESTION_IDS = [
  'audience',
  'tone',
  'lengthSec',
  'keyPoints',
  'visualAesthetic',
  'voiceMood',
  'musicVibe',
];

/* ─── question metadata ──────────────────────────────────────────── */

const QUESTION_META = {
  audience: {
    kind: 'text-or-choice',
    intent: 'Who is this pitch for? Who clicks play?',
  },
  tone: {
    kind: 'choice',
    intent: 'How should the pitch FEEL? Pick the dominant emotional register.',
    fixedOptions: ['Warm & conversational', 'Authoritative & serious', 'Playful & disruptive', 'Cinematic & atmospheric', 'Raw & honest'],
  },
  lengthSec: {
    kind: 'choice',
    intent: 'How long should the finished video be?',
    fixedOptions: ['60', '90', '120'],
  },
  keyPoints: {
    kind: 'multi-text',
    intent: '3–5 things this pitch must communicate. One per line.',
  },
  visualAesthetic: {
    kind: 'choice',
    intent: 'Visual language. Pick the one closest — we will refine.',
    fixedOptions: [
      'Editorial poster (Swiss grid, typographic)',
      'Photographic documentary (35mm, Kodak Portra)',
      'Minimalist studio (clean, high-key product)',
      'Cinematic atmospheric (moody, film noir lighting)',
      'Wes Anderson symmetry (pastel, deadpan)',
      'Brutalist concrete (geometric, hard shadows)',
    ],
  },
  voiceMood: {
    kind: 'choice',
    intent: 'Tone of the narrator voice.',
    fixedOptions: ['Warm', 'Authoritative', 'Playful', 'Lyrical'],
  },
  musicVibe: {
    kind: 'choice',
    intent: 'Music direction. Final samples are picked later — this just sets the brief.',
    fixedOptions: ['Ambient pad (sparse, contemplative)', 'Cinematic orchestral (building, hopeful)', 'Lo-fi acoustic (intimate, warm)', 'Electronic minimal (clean, modern)', 'Hybrid score (textural, modern cinematic)'],
  },
};

const QUESTION_SCHEMA = {
  type: 'object',
  properties: {
    prompt: { type: 'string' },             // the question shown to the user
    helpText: { type: 'string' },           // one-line clarifier
    kind: { type: 'string', enum: ['text', 'choice', 'multi-text', 'text-or-choice'] },
    options: { type: 'array', items: { type: 'string' } },
    suggested: { type: 'string' },          // Gemini's best guess given the seed + prior answers
  },
  required: ['prompt', 'kind'],
};

const STYLESHEET_SCHEMA = {
  type: 'object',
  properties: {
    palette: { type: 'string' },
    typography: { type: 'string' },
    filmRef: { type: 'string' },
    lighting: { type: 'string' },
    texture: { type: 'string' },
    musicTempo: { type: 'string' },
    musicKey: { type: 'string' },
    voiceName: { type: 'string', enum: ['Kore', 'Charon', 'Puck', 'Aoede'] },
    pacing: { type: 'string' },
  },
  required: ['palette', 'typography', 'filmRef', 'lighting', 'texture', 'musicTempo', 'musicKey', 'voiceName', 'pacing'],
};

/* ─── helpers ────────────────────────────────────────────────────── */

function answerIsEmpty(id, answers) {
  const v = answers?.[id];
  if (id === 'keyPoints') return !Array.isArray(v) || v.length === 0;
  if (id === 'lengthSec') return !v;
  return !v || (typeof v === 'string' && !v.trim());
}

function nextUnansweredId(answers) {
  return QUESTION_IDS.find((id) => answerIsEmpty(id, answers)) || null;
}

function buildAdaptivePrompt(id, project) {
  const meta = QUESTION_META[id];
  const prior = JSON.stringify(project.wizardAnswers || {}, null, 2);
  const fixed = meta.fixedOptions ? `\nIf "kind" is choice, use these options verbatim:\n${JSON.stringify(meta.fixedOptions)}` : '';

  return `You are guiding a user through an idea-intake wizard for a 60-second pitch video composer.

The seed idea is: "${project.seedPrompt}"
Prior answers so far:
${prior}

Now write the question metadata for the wizard step "${id}" (intent: ${meta.intent}).

Rules:
- Tailor "prompt" copy to the seed idea — reference it lightly so it feels personalized.
- Fill "kind" exactly as: ${meta.kind}.
- For choice / text-or-choice: provide 4–6 options.${fixed}
- "suggested" should be your best guess given the seed + prior answers (one short value if choice, or a brief example sentence if text). The user can override.
- "helpText" is one short clarifier (≤ 90 chars), no jargon.

Return only the JSON.`;
}

function buildStyleSheetPrompt(project) {
  const a = project.wizardAnswers || {};
  return `Lock the design language for a 60-second pitch video.

Seed idea: "${project.seedPrompt}"

User intake:
- audience: ${a.audience || '(unspecified)'}
- tone: ${a.tone || '(unspecified)'}
- lengthSec: ${a.lengthSec || 60}
- keyPoints: ${(a.keyPoints || []).join(' / ') || '(unspecified)'}
- visualAesthetic: ${a.visualAesthetic || '(unspecified)'}
- voiceMood: ${a.voiceMood || '(unspecified)'}
- musicVibe: ${a.musicVibe || '(unspecified)'}

Produce the locked styleSheet JSON. Each field is a short, evocative descriptor that will be injected into every downstream model call (Nano Banana 2 for slides + b-roll keyframes, Veo 3.1 for motion, Lyria 3 for music, Gemini TTS for narration).

Field guidance:
- palette: 3–5 specific colors with mood ("muted ochre, charcoal shadows, warm gold accent")
- typography: type system + weight ("Helvetica Neue Bold, geometric sans-serif, tight tracking, 200pt headlines")
- filmRef: film stock + camera feel ("Kodak Portra 400, 35mm, slight warm shift")
- lighting: lighting language ("golden hour soft diffused, three-point for products")
- texture: surface treatment ("subtle newsprint grain, halftone overlay")
- musicTempo: BPM + arc ("72 BPM, slow build to midpoint swell")
- musicKey: e.g. "A minor (introspective, hopeful)"
- voiceName: ONE of Kore/Charon/Puck/Aoede that best matches voiceMood. Kore=warm, Charon=authoritative, Puck=playful, Aoede=lyrical.
- pacing: narration cadence ("deliberate, conversational, no rush")

Return only the JSON.`;
}

/* ─── public API ─────────────────────────────────────────────────── */

/**
 * Compute the next question to show the user, or return { complete: true }.
 * Always returns adaptive copy from Gemini Flash; falls back to fixed defaults
 * if the model errors out (the wizard should never block on Flash flakiness).
 */
export async function nextQuestion(project) {
  const id = nextUnansweredId(project.wizardAnswers || {});
  if (!id) return { complete: true };

  const meta = QUESTION_META[id];
  const stepIdx = QUESTION_IDS.indexOf(id);
  const fallback = {
    id,
    prompt: meta.intent,
    helpText: '',
    kind: meta.kind,
    options: meta.fixedOptions || [],
    suggested: '',
    step: stepIdx,
    total: QUESTION_IDS.length,
  };

  try {
    const r = await structuredJSON(
      buildAdaptivePrompt(id, project),
      QUESTION_SCHEMA,
      { name: 'wizard_question', model: PRO_MODEL, strict: false },
    );
    if (!r.ok) throw new Error(r.error);
    const q = r.data || {};
    return {
      id,
      prompt: q.prompt || fallback.prompt,
      helpText: q.helpText || '',
      kind: q.kind || meta.kind,
      options: Array.isArray(q.options) && q.options.length ? q.options : (meta.fixedOptions || []),
      suggested: q.suggested || '',
      step: stepIdx,
      total: QUESTION_IDS.length,
    };
  } catch (e) {
    console.warn('[wizard] adaptive question failed, using fallback:', e?.message || e);
    return fallback;
  }
}

/**
 * Validate + normalize an answer for a given question id.
 * Returns the value to store on project.wizardAnswers[id], or throws.
 */
export function normalizeAnswer(id, raw) {
  if (id === 'keyPoints') {
    const list = Array.isArray(raw)
      ? raw
      : String(raw || '').split('\n').map((s) => s.trim()).filter(Boolean);
    if (list.length < 1) throw new Error('add at least one key point');
    return list.slice(0, 6);
  }
  if (id === 'lengthSec') {
    const n = Number(typeof raw === 'string' ? raw.replace(/[^\d]/g, '') : raw);
    if (![60, 90, 120].includes(n)) throw new Error('lengthSec must be 60, 90, or 120');
    return n;
  }
  const s = String(raw ?? '').trim();
  if (!s) throw new Error(`${id} cannot be empty`);
  return s;
}

/**
 * Lock the project styleSheet from collected wizard answers via Gemini Pro.
 * Throws if the model cannot produce a valid styleSheet — caller should retry
 * or surface to the user.
 */
export async function finalizeStyleSheet(project) {
  const r = await structuredJSON(
    buildStyleSheetPrompt(project),
    STYLESHEET_SCHEMA,
    { name: 'style_sheet', model: PRO_MODEL, strict: true },
  );
  if (r.ok && r.data) return r.data;

  // Loosen strictness once.
  const r2 = await structuredJSON(
    buildStyleSheetPrompt(project),
    STYLESHEET_SCHEMA,
    { name: 'style_sheet', model: PRO_MODEL, strict: false },
  );
  if (!r2.ok) throw new Error(r2.error || 'styleSheet generation failed');
  return r2.data;
}
